Update and rename TROUBLESHOOTING to TROUBLESHOOTING.md
openpredictionmarkets/socialpredict pull request #207
Opened 2024-07-15 03:36 UTC by astrosnat

Added a known issue with running Docker on WSL2.

2024-07-15 13:11 UTC, ntoufoudis requested changes

2024-07-16 04:23 UTC, astrosnat commented on README/TROUBLESHOOTING.md
I'd like to keep in the error message - but how would you have solved it? This is the method that worked for me. I'm sure there's a better one, I just haven't found it...is it something to do with `docker-compose` being deprecated?

2024-07-16 16:21 UTC, pwdel commented on README/TROUBLESHOOTING.md
Hey @astrosnat sorry, so ... yes, docker-compose has been deprecated, I didn't realize that.

With some incoming changes to main which should be finished shortly, the new deploy script will work on both local machines (laptops) and in prod.

So that being said, I don't know if it is supported for Windows or if the changes that you have been working on are going to be incorporated into Windows. I am sorry I have not been following this conversation.

I might be able to help pick this up after @ntoufoudis is done with his contract if he gets to busy to support this issue.

But at the end of the day here, we are definitely going to have a version that is deployable to prod on Digital Ocean now, as well as deployable to local machines for dev purposes.

2024-07-17 02:39 UTC, astrosnat commented on README/TROUBLESHOOTING.md
It's all good! Just glad that there's going to be a version deployable to prod and also deployable to local machines :) if troubleshooting.md gets deprecated in the process, that's fine by me.

2024-07-23 17:53 UTC, pwdel commented
This MR is deprecated in favor of:

https://github.com/openpredictionmarkets/socialpredict/pull/220

2024-07-23 17:53 UTC, closed without merging