Adding usercredit and test.
openpredictionmarkets/socialpredict pull request #346
Opened 2024-09-27 13:38 UTC by pwdel

* Attempting to debug usercredit problem seen on Kenyon instance

2024-09-27 17:00 UTC, pwdel commented
Setup we're working with for test case:

https://github.com/ajlacey/socialpredict/blob/main/backend/setup/setup.yaml

```
economics:
  marketcreation:
    initialMarketProbability: 0.5
    initialMarketSubsidization: 10
    initialMarketYes: 0
    initialMarketNo: 0
  marketincentives:
    createMarketCost: 10
    traderBonus: 1
  user:
    initialAccountBalance: 0
    maximumDebtAllowed: 5000
  betting:
    minimumBet: 1
    betFees:
      initialBetFee: 1
      eachBetFee: 0
      sellSharesFee: 0
```

2024-09-29 03:13 UTC, ajlacey requested changes

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/publicuser/publicuserportfolio.go
consider renaming this file to `portfolio.go` since it is a member of the `publicuser` package.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/publicuser/publicuserportfolio_test.go
No need to add an empty test file. If you're planning to add tests, I would add this file as part of the PR that adds the tests.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/publicuser/publicuser_test.go
> +	}
`NewFakeDB(t)` migrates the models on creation, so this is redundant.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/privateuserinfo/privateuser_test.go
same as publicuser_test- this isn't necessary unless you're adding tests. Since there is no new privateuser code here, I think it makes sense to add this when we create tests for the privateuser package.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/credit/usercredit_test.go
> +package usercredit_test
I don't think this should be a separate package. We're not exporting test functionality here.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/credit/usercredit.go
> +func CalculateUserCredit(db *gorm.DB, username string, maximumdebt int64) int64 {
This function can remain private when the testing is done in the same package.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/credit/usercredit_test.go
> +	}
db migration happens when creating the fake.

2024-09-29 03:13 UTC, ajlacey commented on backend/handlers/users/credit/usercredit_test.go
> +			ApiKey:         test.apiKey,
Is this field necessary to create a user? It doesn't look like it, but I may misunderstand the gorm struct tagging. If it's not necessary, I don't think we're using this field in the tests at all and can safely remove it.

2024-10-09 21:28 UTC, pwdel commented
Replaced with https://github.com/openpredictionmarkets/socialpredict/pull/368

2024-10-09 21:28 UTC, closed without merging